#!/bin/bash

BASH_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -z $U18ENV_IMAGE_NAME ]; then
    U18ENV_IMAGE_NAME=ubuntu18-env:latest
fi

if [ -z $U18ENV_CONTAINER_NAME ]; then
    U18ENV_CONTAINER_NAME=ubuntu18-env
fi


docker run -itd \
    -e VNC_RESOLUTION=1920x1080 \
    -e VNC_PW=password \
    -v "$HOME/3d_features:/home/user/3d_features" \
    -v "$HOME/notebooks:/home/user/notebooks" \
    -v "$HOME/pose-graph-repository:/home/user/pose-graph-repository" \
    --net host \
    --gpus all \
    -v /dev:/dev \
    -v /:/hostroot \
    --name $U18ENV_CONTAINER_NAME \
    --privileged \
    $U18ENV_IMAGE_NAME
